blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/edit',
         views.profile_edit, name='profile_edit'),
    path('profile/<str:username>/followers/',
         views.profile_followers, name='profile_followers'),
    path('profile/<str:username>/followings/',
         views.profile_followings, name='profile_followings'),
    path('profile/<str:username>/profile-group-list/',
         views.profile_group_list, name='profile_group_list'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', views.post_like, name='post_like'),
    path('posts/<int:post_id>/dislike/',
         views.post_dislike, name='post_dislike'),
    path('posts/<int:post_id>/likes/', views.post_likes, name='post_likes'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/search/', views.post_search, name='post_search'),
    path('groups/', views.groups_list, name='groups_list'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/follow/', views.group_follow, name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow, name='group_unfollow'),
    path('group/<slug:slug>/members/',
         views.group_members, name='group_members'),
    path('group/<slug:slug>/members-m/',
         views.group_role_m, name='group_role_m'),
    path('group/<slug:slug>/administrators/',
         views.group_administrators, name='group_administrators'),
    path('group/<slug:slug>/edit/', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/delete/', views.group_delete, name='group_delete'),
    path('group/<slug:slug>/add-administrator/<str:username>/',
         views.group_add_administrator, name='group_add_administrator'),
    path('group/<slug:slug>/demote-administrator/',
         views.group_demote_administrator, name='group_demote_administrator'),
    path('group-create/', views.group_create, name='group_create'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('groups-follow/',
         views.group_follow_index, name='group_follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('comment/<int:comment_id>/edit/',
         views.comment_edit, name='comment_edit'),
    path('comment/<int:comment_id>/delete/',
         views.comment_delete, name='comment_delete'),
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from users import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    )
]

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import F, Q

from posts.validators import validate_not_empty


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    members = models.ManyToManyField(User, through='Membership')

    def __str__(self) -> str:
        return self.title


class Membership(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)
    ROLES = (
        ('a', 'administrator'),
        ('m', 'member')
    )
    role = models.CharField(max_length=1, choices=ROLES, default='m')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['group', 'member'], name='already_subscribed'),
        ]


class Post(models.Model):
    text = models.TextField(
        db_index=True,
        validators=[validate_not_empty],
        verbose_name='Текст поста',
        help_text='Текст нового поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True,
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~Q(user=F('author')), name='anti_self_sub'),
            models.UniqueConstraint(
                fields=['user', 'author'], name='only_one_sub'),
        ]


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'], name='only_one_like'),
        ]

posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from posts.models import Comment, Group, Post


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'slug', 'description',)

templates/posts/comment_delete.html
{% extends "base.html" %}
{% block title %}Удалить комментарий?{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">Удалить комментарий?</div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
              <a class="btn btn-primary me-2"
                 href="{% url 'posts:post_detail' comment.post.id %}">Нет</a>
              <button type="submit" class="btn btn-danger">Да</button>
              &nbsp;
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста
                <span class="required text-danger">*</span>
              </label>
              {{ form.text }}
              <small id="id_text-help" class="form-text text-muted">Текст нового поста</small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_group">Группа</label>
              {{ form.group }}
              <small id="id_group-help" class="form-text text-muted">Группа, к которой будет относиться пост</small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image">Изображение</label>
              {{ form.image|addclass:"form-control" }}
              <small id="id_image-help" class="form-text text-muted">По желанию добавьте изображение</small>
            </div>
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Подписки на пользователей{% endblock %}
{% block content %}
  <h1>Подписки на пользователей</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/group_administrators.html
{% extends "base.html" %}
{% block title %}Администраторы группы {{ group.title }} ({{ administrators.count }}){% endblock %}
{% block content %}
  <h3>Администраторы группы {{ group.title }} ({{ administrators.count }})</h3>
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:group_posts' group.slug %}">Вернуться к группе</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for administrator in administrators %}
        {% if administrator.get_full_name %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' administrator.username %}">{{ administrator.get_full_name }}</a>
          </li>
        {% else %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' administrator.username %}">{{ administrator.username }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/posts/group_follow_index.html
{% extends "base.html" %}
{% block title %}Подписки на группы{% endblock %}
{% block content %}
  <h1>Подписки на группы</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/group_role_m.html
{% extends "base.html" %}
{% block title %}Участники группы {{ group.title }}{% endblock %}
{% block content %}
  <h3>Участники группы {{ group.title }}</h3>
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:group_posts' group.slug %}">Вернуться к группе</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for member in members %}
        <li class="list-group-item">
          <a class="text-decoration-none"
             href="{% url 'posts:group_add_administrator' group.slug member.username %}">{{ member.username }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block title %}Лента{% endblock %}
{% block content %}
  <h1>Лента</h1>
  {% if not user.is_authenticated %}<hr />{% endif %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/post_detail.html
{% extends "base.html" %}
{% load tz %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Автор: <a href="{% url 'posts:profile' post.author.username %}"
    class="text-decoration-none">
          {% if post.author.get_full_name %}
            {{ post.author.get_full_name }}
          {% else %}
            {{ post.author.username }}
          {% endif %}
        </a>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
      {% if post.group %}
        <li class="list-group-item">
          Группа: <a href="{% url 'posts:group_posts' post.group.slug %}"
    class="text-decoration-none">{{ post.group.title }}</a>
        </li>
      {% endif %}
      <li class="list-group-item">
        {% if request.COOKIES.timezone %}
          {% timezone request.COOKIES.timezone %}
          <p>
            <a href="{% url 'posts:post_detail' post.id %}"
               class="text-decoration-none">{{ post.pub_date|date:"d E Y H:i" }}</a>
          </p>
        {% endtimezone %}
      {% else %}
        <p>
          <a href="{% url 'posts:post_detail' post.id %}"
             class="text-decoration-none">{{ post.pub_date|date:"d E Y H:i" }}</a>
        </p>
      {% endif %}
    </li>
  </ul>
</aside>
<article class="col-12 col-md-9">
  <br>
  <p>{{ post.text|safe|linebreaksbr }}</p>
  {% if post.image %}
    <div class="text-center">
      <img class="card-img mb-4 mt-4"
           src="{{ post.image.url }}"
           style="object-fit: contain;
                  max-height:480px">
    </div>
  {% endif %}
  <ul id="likes" class="list-group list-group-horizontal-sm mb-2">
    {% if post.likes.count > 0 %}
      <li class="dropdown list-group-item">
        <a class="text-decoration-none text-dark dropdown-toggle"
           href="#"
           role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">Лайки: {{ post.likes.count }}</a>
        <ul class="dropdown-menu">
          {% for like in likes %}
            {% if like.user.get_full_name %}
              <li>
                <a class="dropdown-item"
                   href="{% url 'posts:profile' like.user.username %}">{{ like.user.get_full_name }}</a>
              </li>
            {% else %}
              <li>
                <a class="dropdown-item"
                   href="{% url 'posts:profile' like.user.username %}">{{ like.user.username }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if post.likes.count > likes_num %}
            <li>
              <a class="dropdown-item" href="{% url 'posts:post_likes' post.id %}">Посмотреть все</a>
            </li>
          {% endif %}
        </ul>
      </li>
    {% else %}
      <li class="list-group-item">Лайки: 0</li>
    {% endif %}
    <li class="list-group-item">Комментарии: {{ post.comments.count }}</li>
  </ul>
  {% if not user.is_authenticated %}
    <br>
    <a href="{% url 'users:login' %}" class="text-decoration-none">Войдите, чтобы поставить лайк или прокомментировать</a>
  {% else %}
    {% if liked %}
      <a href="{% url 'posts:post_dislike' post.id %}"
         class="btn btn-secondary mb-2 mt-2 me-2">Дизлайк</a>
    {% else %}
      <a href="{% url 'posts:post_like' post.id %}"
         class="btn btn-primary mb-2 mt-2 me-2">Поставить 👍</a>
    {% endif %}
  {% endif %}
  {% if user == post.author %}
    <br>
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
    <br>
    <!-- Button trigger modal -->
    <button type="button"
            class="btn btn-danger mb-2 mt-2 me-2"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal">Удалить пост</button>
    <!-- Modal -->
    <div class="modal fade"
         id="exampleModal"
         tabindex="-1"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Удалить пост?</h1>
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
            <form method="post" action="{% url 'posts:post_delete' post.id %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Да</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  <div id="comments">{% include 'posts/includes/comments.html' %}</div>
</article>
</div>
{% endblock %}

templates/posts/post_likes.html
{% extends "base.html" %}
{% block title %}Лайки поста {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <h3>Оценили {{ likes.count }}</h3>
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:post_detail' post.id %}">Вернуться к посту</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for like in likes %}
        {% if like.user.get_full_name %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' like.user.username %}">{{ like.user.get_full_name }}</a>
          </li>
        {% else %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' like.user.username %}">{{ like.user.username }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/posts/post_search.html
{% extends "base.html" %}
{% block title %}Поиск по запросу: {{ search_text|truncatechars:30 }}{% endblock %}
{% block content %}
  <h1>Поиск по запросу: {{ search_text }}</h1>
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя
  {% if author.get_full_name %}
    {{ author.get_full_name }}
  {% else %}
    {{ author.username }}
  {% endif %}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>
      Профиль пользователя
      {% if author.get_full_name %}
        {{ author.get_full_name }}
      {% else %}
        {{ author.username }}
      {% endif %}
    </h1>
    <ul class="list-group list-group-horizontal-sm mb-2">
      <li class="list-group-item">Публикации: {{ author.posts.count }}</li>
      <a class="link-primary list-group-item"
         href="{% url 'posts:profile_group_list' author.username %}">Группы: {{ groups_count }}</a>
      <a class="link-primary list-group-item"
         href="{% url 'posts:profile_followers' author.username %}">Подписчики: {{ author.following.count }}</a>
      <a class="link-primary list-group-item"
         href="{% url 'posts:profile_followings' author.username %}">Подписки: {{ author.follower.count }}</a>
    </ul>
    {% if user != author %}
      {% if following %}
        <a class="btn btn-lg btn-secondary"
           href="{% url 'posts:profile_unfollow' author.username %}"
           role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}"
           role="button">Подписаться</a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'posts/includes/article.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

templates/posts/profile_followers.html
{% extends "base.html" %}
{% block title %}
  {% if profile_user.get_full_name %}
    Подписчики пользователя {{ profile_user.get_full_name }} ({{ followers.count }})
  {% else %}
    Подписчики пользователя {{ profile_user.username }} ({{ followers.count }})
  {% endif %}
{% endblock %}
{% block content %}
  {% if profile_user.get_full_name %}
    <h3>Подписчики пользователя {{ profile_user.get_full_name }} ({{ followers.count }})</h3>
  {% else %}
    <h3>Подписчики пользователя {{ profile_user.username }} ({{ followers.count }})</h3>
  {% endif %}
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:profile' profile_user.username %}">Вернуться к профилю</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for follower in followers %}
        {% if follower.user.get_full_name %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' follower.user.username %}">{{ follower.user.get_full_name }}</a>
          </li>
        {% else %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' follower.user.username %}">{{ follower.user.username }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/posts/profile_followings.html
{% extends "base.html" %}
{% block title %}
  {% if profile_user.get_full_name %}
    Подписки пользователя {{ profile_user.get_full_name }} ({{ followings.count }})
  {% else %}
    Подписки пользователя {{ profile_user.username }} ({{ followings.count }})
  {% endif %}
{% endblock %}
{% block content %}
  {% if profile_user.get_full_name %}
    <h3>Подписки пользователя {{ profile_user.get_full_name }} ({{ followings.count }})</h3>
  {% else %}
    <h3>Подписки пользователя {{ profile_user.username }} ({{ followings.count }})</h3>
  {% endif %}
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:profile' profile_user.username %}">Вернуться к профилю</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for following in followings %}
        {% if following.author.get_full_name %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' following.author.username %}">{{ following.author.get_full_name }}</a>
          </li>
        {% else %}
          <li class="list-group-item">
            <a class="text-decoration-none"
               href="{% url 'posts:profile' following.author.username %}">{{ following.author.username }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
{% endblock %}

templates/posts/profile_group_list.html
{% extends "base.html" %}
{% block title %}
  {% if profile_user.get_full_name %}
    Группы пользователя {{ profile_user.get_full_name }} ({{ groups.count }})
  {% else %}
    Группы пользователя {{ profile_user.username }} ({{ groups.count }})
  {% endif %}
{% endblock %}
{% block content %}
  {% if profile_user.get_full_name %}
    <h3>Группы пользователя {{ profile_user.get_full_name }} ({{ groups.count }})</h3>
  {% else %}
    <h3>Группы пользователя {{ profile_user.username }} ({{ groups.count }})</h3>
  {% endif %}
  <div class="d-flex justify-content-start">
    <a class="btn btn-primary mb-2 mt-2 me-2"
       href="{% url 'posts:profile' profile_user.username %}">Вернуться к профилю</a>
  </div>
  <div class="d-flex justify-content-around">
    <ul class="list-group">
      {% for group in groups %}
        <li class="list-group-item">
          <a class="text-decoration-none"
             href="{% url 'posts:group_posts' group.slug %}">{{ group.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}