blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/edit',
         views.profile_edit, name='profile_edit'),
    path('profile/<str:username>/followers/',
         views.profile_followers, name='profile_followers'),
    path('profile/<str:username>/followings/',
         views.profile_followings, name='profile_followings'),
    path('profile/<str:username>/profile-group-list/',
         views.profile_group_list, name='profile_group_list'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', views.post_like, name='post_like'),
    path('posts/<int:post_id>/dislike/',
         views.post_dislike, name='post_dislike'),
    path('posts/<int:post_id>/likes/', views.post_likes, name='post_likes'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/search/', views.post_search, name='post_search'),
    path('groups/', views.groups_list, name='groups_list'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/follow/', views.group_follow, name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow, name='group_unfollow'),
    path('group/<slug:slug>/members/',
         views.group_members, name='group_members'),
    path('group/<slug:slug>/members-m/',
         views.group_role_m, name='group_role_m'),
    path('group/<slug:slug>/administrators/',
         views.group_administrators, name='group_administrators'),
    path('group/<slug:slug>/edit/', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/delete/', views.group_delete, name='group_delete'),
    path('group/<slug:slug>/add-administrator/<str:username>/',
         views.group_add_administrator, name='group_add_administrator'),
    path('group/<slug:slug>/demote-administrator/',
         views.group_demote_administrator, name='group_demote_administrator'),
    path('group-create/', views.group_create, name='group_create'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('groups-follow/',
         views.group_follow_index, name='group_follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('comment/<int:comment_id>/edit/',
         views.comment_edit, name='comment_edit'),
    path('comment/<int:comment_id>/delete/',
         views.comment_delete, name='comment_delete'),
]

templates/includes/footer.html
<p>©{{ year }} Copyright blog</p>

templates/includes/header.html
{% load static %}
{% load user_filters %}
{% with request.resolver_match.view_name as view_name %}
  <header>
    <nav class="navbar navbar-expand-lg navbar-light"
         style="background-color: lightskyblue">
      <div class="container-fluid ps-5 pe-5" style="max-width:1080px;">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}"
               width="30"
               height="30"
               class="d-inline-block align-top"
               alt="" />
          blog
        </a>
        <button class="navbar-toggler mb-1 mt-1"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav nav-pills nav-fill">
            <li class="nav-item mb-1 mt-1 ms-1 me-1">
              <a class="nav-link {% if view_name == 'posts:index' %}active{% endif %}"
                 href="{% url 'posts:index' %}"><span style="color: white">Лента</span></a>
            </li>
            <li class="nav-item mb-1 mt-1 ms-1 me-1">
              <a class="nav-link {% if view_name == 'posts:groups_list' %}active{% endif %}"
                 href="{% url 'posts:groups_list' %}"><span style="color: white">Группы</span></a>
            </li>
            <li class="nav-item mb-1 mt-1 ms-1 me-1">
              <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
                 href="{% url 'about:author' %}"><span style="color: white">Об авторе</span></a>
            </li>
            <li class="nav-item mb-1 mt-1 ms-1 me-1">
              <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
                 href="{% url 'about:tech' %}"><span style="color: white">Технологии</span></a>
            </li>
            <li class="nav-item dropdown mb-1 mt-1 ms-1 me-1">
              <!-- dropend вместо dropdown чтобы вправо -->
              <a href="#"
                 class="nav-link dropdown-toggle {% if view_name == 'posts:post_search' %}active{% endif %}"
                 id="navbarDrop"
                 role="button"
                 data-bs-toggle="dropdown"
                 aria-expanded="false"
                 style="color: white">Поиск</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDrop">
                <li>
                  <form action="{% url 'posts:post_search' %}"
                        class="d-flex justify-content-center"
                        method="get">
                    <input type="search"
                           placeholder="Искать в постах"
                           class="form-control ms-2"
                           style="width: 175px"
                           name="search_text"
                           required>
                    <button class="btn btn-outline-primary mb-1 mt-1 ms-2 me-2">Поиск</button>
                  </form>
                </li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav nav-pills nav-fill ms-auto">
            {% if user.is_authenticated %}
              <div class="dropdown nav-item">
                <button type="button"
                        style="color: white"
                        class="nav-link dropdown-toggle {% if view_name == 'posts:profile' and author == request.user %}active{% endif %} {% if view_name == 'posts:post_create' %}active{% endif %} {% if view_name == 'posts:profile_edit' %}active{% endif %} {% if view_name == 'users:password_change_form' %}active{% endif %} {% if view_name == 'users:logout' %}active{% endif %}"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{{ user.username }}</button>
                <ul class="dropdown-menu dropdown-menu-end text-center ms-auto"
                    aria-labelledby="navbarDrop">
                  <li>
                    <a href="{% url 'posts:profile' user.username %}"
                       class="dropdown-item {% if view_name == 'posts:profile' and author == request.user %}active{% endif %} mb-1 mt-1">Страница пользователя</a>
                  </li>
                  <li>
                    <a href="{% url 'posts:post_create' %}"
                       class="dropdown-item {% if view_name == 'posts:post_create' %}active{% endif %} mb-1 mt-1">Новая запись</a>
                  </li>
                  <li>
                    <a href="{% url 'posts:profile_edit' user.username %}"
                       class="dropdown-item {% if view_name == 'posts:profile_edit' %}active{% endif %} mb-1 mt-1">Редактировать профиль</a>
                  </li>
                  <li>
                    <a href="{% url 'users:password_change_form' %}"
                       class="dropdown-item {% if view_name == 'users:password_change_form' %}active{% endif %} mb-1 mt-1">Изменить пароль</a>
                  </li>
                  <li>
                    {% comment %} <a href="{% url 'users:logout' %}" class="dropdown-item {% if view_name == 'users:logout' %}active{% endif %} mb-1 mt-1">Выйти</a> {% endcomment %}
                    <form action="{% url 'users:logout' %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="dropdown-item mb-1 mt-1">Выйти</button>
                    </form>
                  </li>
                </ul>
              </div>
            {% else %}
              <li class="nav-item mb-1 mt-1 ms-1 me-1">
                <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}"
                   href="{% url 'users:login' %}"><span style="color: white">Войти</span></a>
              </li>
              <li class="nav-item mb-1 mt-1 ms-1 me-1">
                <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}"
                   href="{% url 'users:signup' %}"><span style="color: white">Регистрация</span></a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
{% endwith %}