blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

posts/urls.py
from django.urls import path

from posts import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/edit',
         views.profile_edit, name='profile_edit'),
    path('profile/<str:username>/followers/',
         views.profile_followers, name='profile_followers'),
    path('profile/<str:username>/followings/',
         views.profile_followings, name='profile_followings'),
    path('profile/<str:username>/profile-group-list/',
         views.profile_group_list, name='profile_group_list'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', views.post_like, name='post_like'),
    path('posts/<int:post_id>/dislike/',
         views.post_dislike, name='post_dislike'),
    path('posts/<int:post_id>/likes/', views.post_likes, name='post_likes'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/search/', views.post_search, name='post_search'),
    path('groups/', views.groups_list, name='groups_list'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('group/<slug:slug>/follow/', views.group_follow, name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow, name='group_unfollow'),
    path('group/<slug:slug>/members/',
         views.group_members, name='group_members'),
    path('group/<slug:slug>/members-m/',
         views.group_role_m, name='group_role_m'),
    path('group/<slug:slug>/administrators/',
         views.group_administrators, name='group_administrators'),
    path('group/<slug:slug>/edit/', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/delete/', views.group_delete, name='group_delete'),
    path('group/<slug:slug>/add-administrator/<str:username>/',
         views.group_add_administrator, name='group_add_administrator'),
    path('group/<slug:slug>/demote-administrator/',
         views.group_demote_administrator, name='group_demote_administrator'),
    path('group-create/', views.group_create, name='group_create'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('groups-follow/',
         views.group_follow_index, name='group_follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('comment/<int:comment_id>/edit/',
         views.comment_edit, name='comment_edit'),
    path('comment/<int:comment_id>/delete/',
         views.comment_delete, name='comment_delete'),
]

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import F, Q

from posts.validators import validate_not_empty


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    members = models.ManyToManyField(User, through='Membership')

    def __str__(self) -> str:
        return self.title


class Membership(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now_add=True)
    ROLES = (
        ('a', 'administrator'),
        ('m', 'member')
    )
    role = models.CharField(max_length=1, choices=ROLES, default='m')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['group', 'member'], name='already_subscribed'),
        ]


class Post(models.Model):
    text = models.TextField(
        db_index=True,
        validators=[validate_not_empty],
        verbose_name='Текст поста',
        help_text='Текст нового поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True,
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~Q(user=F('author')), name='anti_self_sub'),
            models.UniqueConstraint(
                fields=['user', 'author'], name='only_one_sub'),
        ]


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='likes',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'], name='only_one_like'),
        ]

posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from posts.models import Comment, Group, Post


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'slug', 'description',)

posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods

from posts.forms import CommentForm, GroupForm, PostForm, ProfileForm
from posts.models import Comment, Follow, Group, Like, Membership, Post, User
from posts.utils import paginator_func


def index(request):
    post_list = Post.objects.all().prefetch_related(
        'author', 'group', 'comments', 'likes')
    page_obj = paginator_func(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all().prefetch_related(
        'author', 'group', 'comments', 'likes')
    page_obj = paginator_func(request, post_list)
    memberships = Membership.objects.filter(group=group)
    administrators_count = memberships.filter(role='a').count()
    members_count = memberships.count()
    if (request.user.is_authenticated
       and memberships.filter(member=request.user).exists()):
        membership = memberships.get(member=request.user)
    else:
        membership = None
    context = {
        'group': group,
        'page_obj': page_obj,
        'membership': membership,
        'administrators_count': administrators_count,
        'members_count': members_count,
    }
    return render(request, 'posts/group_posts.html', context)


@login_required
def group_create(request):
    form = GroupForm(
        request.POST or None,
    )
    if not form.is_valid():
        return render(request, 'posts/group_create.html', {'form': form})
    group = form.save(commit=False)
    group.save()
    group = Group.objects.get(slug=group.slug)
    group.members.add(request.user, through_defaults={'role': 'a'})
    return redirect('posts:group_posts', slug=group.slug)


@login_required
def group_edit(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if Membership.objects.get(group=group, member=request.user).role != 'a':
        return redirect('posts:group_posts', slug=group.slug)
    form = GroupForm(
        request.POST or None,
        instance=group,
    )
    context = {
        'form': form,
        'is_edit': True
    }
    if not form.is_valid():
        return render(request, 'posts/group_create.html', context)
    form.save()
    return redirect('posts:group_posts', slug=group.slug)


@login_required
@require_http_methods(["POST"])
def group_delete(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if Membership.objects.get(group=group, member=request.user).role != 'a':
        return redirect('posts:group_posts', slug=group.slug)
    group.delete()
    return redirect('posts:index')


@login_required
def group_follow(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if not Membership.objects.filter(group=group,
                                     member=request.user).exists():
        Membership.objects.create(group=group, member=request.user)
    return redirect('posts:group_posts', slug=group.slug)


@login_required
def group_unfollow(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if (Membership.objects.filter(group=group,
                                  member=request.user).exists()
        and Membership.objects.get(group=group,
                                   member=request.user).role != 'a'):
        Membership.objects.filter(group=group, member=request.user).delete()
    return redirect('posts:group_posts', slug=group.slug)


def group_administrators(request, slug):
    group = get_object_or_404(Group, slug=slug)
    administrators = group.members.filter(membership__role='a')
    context = {
        'group': group,
        'administrators': administrators,
    }
    return render(request, 'posts/group_administrators.html', context)


def group_members(request, slug):
    group = get_object_or_404(Group, slug=slug)
    members = group.members.all()
    context = {
        'group': group,
        'members': members,
    }
    return render(request, 'posts/group_members.html', context)


@login_required
def group_role_m(request, slug):
    group = get_object_or_404(Group, slug=slug)
    members = User.objects.filter(
        group=group, membership__role='m').order_by('username')
    context = {
        'group': group,
        'members': members,
    }
    return render(request, 'posts/group_role_m.html', context)


@login_required
def group_add_administrator(request, slug, username):
    group = get_object_or_404(Group, slug=slug)
    member = get_object_or_404(User, username=username)
    if (Membership.objects.filter(group=group,
                                  member=request.user).exists()
        and Membership.objects.get(group=group,
                                   member=request.user).role == 'a'
            and Membership.objects.filter(group=group,
                                          member=member).exists()):
        membership = Membership.objects.get(group=group, member=member)
        membership.role = 'a'
        membership.save()
    return redirect('posts:group_posts', slug=group.slug)


@login_required
def group_demote_administrator(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if (Membership.objects.filter(group=group,
                                  member=request.user).exists()
        and Membership.objects.get(group=group,
                                   member=request.user).role == 'a'
            and Membership.objects.filter(group=group, role='a').count() > 1):
        membership = Membership.objects.get(group=group, member=request.user)
        membership.role = 'm'
        membership.save()
    return redirect('posts:group_posts', slug=group.slug)


def groups_list(request):
    context = {
        'groups': Group.objects.all().order_by('title'),
    }
    return render(request, 'posts/groups_list.html', context)


@login_required
def group_follow_index(request):
    groups = Group.objects.filter(
        members=request.user).values_list('slug', flat=True)
    post_list = Post.objects.prefetch_related(
        'author', 'group', 'comments', 'likes').filter(group__slug__in=groups)
    page_obj = paginator_func(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_follow_index.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    groups_count = Group.objects.filter(members=user).count()
    user_posts = user.posts.all()
    page_obj = paginator_func(request, user_posts)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=user).exists()
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
        'groups_count': groups_count,
    }
    return render(request, 'posts/profile.html', context)


def profile_group_list(request, username):
    user = get_object_or_404(User, username=username)
    groups = Group.objects.filter(members=user).order_by('title')
    context = {
        'profile_user': user,
        'groups': groups,
    }
    return render(request, 'posts/profile_group_list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    likes = post.likes.order_by('-created')[:settings.LIKES_VIEW_NUM]
    liked = False
    if request.user.is_authenticated:
        liked = Like.objects.filter(
            post=post, user=request.user).exists()
    context = {
        'post': post,
        'form': CommentForm(request.POST),
        'comments': post.comments.all(),
        'liked': liked,
        'likes': likes,
        'likes_num': settings.LIKES_VIEW_NUM,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:post_detail',
                    post_id=request.user.posts.order_by('pk').last().id)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'is_edit': True
    }
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
@require_http_methods(["POST"])
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    post.delete()
    return redirect('posts:profile', username=request.user)


@require_http_methods(["GET"])
def post_search(request):
    search_text = request.GET.get('search_text')
    if search_text is None:
        return redirect('posts:index')
    post_list = Post.objects.filter(text__icontains=search_text)
    page_obj = paginator_func(request, post_list)
    context = {
        'page_obj': page_obj,
        'search_text': search_text
    }
    return render(request, 'posts/post_search.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post

templates/posts/includes/article.html
{% load tz %}
{% load user_filters %}
<article>
  <h4>
    <a href="{% url 'posts:profile' post.author.username %}"
       class="text-decoration-none">
      {% if post.author.get_full_name %}
        {{ post.author.get_full_name }}
      {% else %}
        {{ post.author.username }}
      {% endif %}
    </a>
  </h4>
  {% if post.group %}
    <h5>
      Для группы <a href="{% url 'posts:group_posts' post.group.slug %}"
    class="text-decoration-none">{{ post.group.title }}</a>
    </h5>
  {% endif %}
  <br>
  {{ post.text|safe|linebreaksbr }}
  <br>
  {% if post.image %}
    <div class="text-center">
      <img class="card-img mb-4 mt-4"
           src="{{ post.image.url }}"
           style="object-fit: contain;
                  max-height:480px">
    </div>
  {% endif %}
  {% if timezone %}
    {% timezone timezone %}
    <p>
      <a href="{% url 'posts:post_detail' post.id %}"
         class="text-decoration-none">{{ post.pub_date|date:"d E Y H:i" }}</a>
    </p>
  {% endtimezone %}
{% elif request.COOKIES.timezone %}
  {% timezone request.COOKIES.timezone %}
  <p>
    <a href="{% url 'posts:post_detail' post.id %}"
       class="text-decoration-none">{{ post.pub_date|date:"d E Y H:i" }}</a>
  </p>
{% endtimezone %}
{% else %}
<p>
  <a href="{% url 'posts:post_detail' post.id %}"
     class="text-decoration-none">{{ post.pub_date|date:"d E Y H:i" }}</a>
</p>
{% endif %}
<ul class="list-group list-group-horizontal-sm mb-2">
  <a class="link-primary list-group-item"
     href="{% url 'posts:post_detail' post.id %}#likes">Лайки: {{ post.likes.count }}</a>
  <a class="link-primary list-group-item"
     href="{% url 'posts:post_detail' post.id %}#comments">Комментарии: {{ post.comments.count }}</a>
</ul>
{% if not forloop.last %}<hr />{% endif %}
</article>

templates/posts/includes/comments.html
{% load user_filters %}
{% load tz %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">{{ form.text|addclass:"form-control" }}</div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0 d-flex justify-content-start">
        <a class="text-decoration-none"
           href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
      </h5>
      <p>{{ comment.text|linebreaksbr }}</p>
      {% if request.COOKIES.timezone %}
        {% timezone request.COOKIES.timezone %}
        <p>
          <small>{{ comment.created|date:"d E Y H:i" }}</small>
        </p>
      {% endtimezone %}
    {% else %}
      <p>
        <small>{{ comment.created|date:"d E Y H:i" }}</small>
      </p>
    {% endif %}
    {% if comment.author == user %}
      <a class="btn btn-sm btn-primary mb-1 me-1"
         href="{% url 'posts:comment_edit' comment.id %}">Редактировать</a>
      <a class="btn btn-sm btn-danger mb-1 me-1"
         href="{% url 'posts:comment_delete' comment.id %}">Удалить</a>
    {% endif %}
  </div>
</div>
{% if not forloop.last %}<hr />{% endif %}
{% endfor %}

templates/posts/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/posts/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
  {% if user.is_authenticated %}
    <div class="row my-3">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:index' %}active{% endif %}"
             href="{% url 'posts:index' %}">Вся лента</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:follow_index' %}active{% endif %}"
             href="{% url 'posts:follow_index' %}">Избранные авторы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:group_follow_index' %}active{% endif %}"
             href="{% url 'posts:group_follow_index' %}">Избранные группы</a>
        </li>
      </ul>
    </div>
  {% endif %}
{% endwith %}